### PR TITLE
New validation

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?180215#1003031

cc: @czue

### CODE REVIEW

**Comment by czue** [comment]
(needs to be updated for backwards compatibility so put a don't merge on it. @emord let me know when you're ready for re-review)

**Comment by emord** [comment]
Decided to just write both forms to each form

**Comment by czue** [comment]
@wpride can you confirm the addition of the `<alert>` won't break the older versions as long as the attribute format is also present?

**Comment by wpride** [comment]
@czue confirmed that if an <alert> block is present in a resource when an older version installs it'll just be ignored

**Comment by czue** [comment]
thanks!

**Pull request merged**
