### PR TITLE
Show help on click and link at bottom of text

### PR DESCRIPTION
**Pull request by emord**
@orangejenny I'm pulling this from the markdown work we did yesterday into this PR. I think you talked to @amsagoff already correct?

This changes the help bubbles in vellum to have a see more link at the end of the help text and the button now shows up once you click it instead of hover. 

cc @czue

### CODE REVIEW

**Comment by millerdev** [comment]
Would it be easy to make it hide the help bubble if you click the question mark a second time?

**Comment by czue** [comment]
:+1: from me - will let @millerdev merge when he's happy

**Comment by orangejenny** [comment]
@millerdev The help bubble is hidden when you click anywhere on the page - should include clicking on the question mark itself

@emord I agree this makes more sense as a separate PR, but @amsagoff wanted some UAT feedback before fully releasing because it's such a broad change, so this shouldn't get merged into master just yet. And when it does go out, HQ's help bubbles ought to be updated on the same deploy.

**Comment by millerdev** [comment]
> The help bubble is hidden when you click anywhere on the page

It didn't work that way when I tested this branch locally.

**Comment by orangejenny** [comment]
@millerdev My mistake, the behavior is to close the bubble when you click anywhere else on the page...*except* for re-clicking on the link itself. And these help links include quite a bit of whitespace around the icon.

Added a commit to wrap the each help link in a div so it gets placed correctly on the page but only the icon itself is hoverable/clickable, which should make it less annoying.

**Comment by emord** [comment]
@orangejenny 

> wanted some UAT feedback before fully releasing because it's such a broad change

Sorry. Missed that part of our convo. Would you like to head up UAT on this? You have more context on this

**Comment by orangejenny** [comment]
@emord sure

**Comment by orangejenny** [comment]
Closing in favor of https://github.com/dimagi/Vellum/pull/451 - turned out to be easier to cherry-pick a new branch than to rebase this one.

**Pull request closed without merging**
