### PR TITLE
Ellipsis on drag helper

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?243355

screen shot 2016-12-06 at 2 42 56 pm

### CODE REVIEW

**Comment by millerdev** [comment]
Yay! I love this solution. Thanks @orangejenny

**Comment by millerdev** [comment]
😞 conflict?

**Comment by orangejenny** [comment]
So I just pulled master, merged it in (although no conflicts showed up), and pushed, and this is now marked both closed and merged. Odd. I just ran tests locally on master, and they're fine. Killed travis.

**Comment by proteusvacuum** [comment]
🎉

**Pull request closed without merging**
