### PR TITLE
Don't show data value when there isn't one defined

### PR DESCRIPTION
**Pull request by emord**
https://groups.google.com/forum/#!topic/commcare-users/uPdIy-9SQUk

cc: @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
haha noticed this one last night when reading that email

**Comment by benrudolph** [comment]
i couldn't figure out the difference though. one allows you to reference /data/ and the other doesn't? the one that loads via /data/ seems obsolete and should just be done via case mgmt

**Comment by emord** [comment]
Default Data Value writes a string in the data tree to that node. You can only use it for strings and xpaths. It's legacy

Default Value uses `setvalue` so you can use xpath expresions for the same thing, but also have the power to reference cases/fixtures/whatever inside vellum. The help message actually tells you that using /data/ could be an issue and isn't supported. (used to be a warning/error, but vellum doesn't currently have a distinction between the two and it was getting in the way of some other forms.)

**Comment by benrudolph** [comment]
cool thanks for the explanation

**Comment by benrudolph** [comment]
good after tests

**Pull request merged**
