### PR TITLE
Bump add choice left

### PR DESCRIPTION
**Pull request by orangejenny**
@biyeun any objections to this? Suggestion from @benrudolph to make the "Add Choice" look less like a choice itself.

screen shot 2017-03-14 at 9 41 07 am

### CODE REVIEW

**Comment by benrudolph** [comment]
ah sorry i actually meant the other way so it's on the same hierarchy plane as the choice

**Comment by benrudolph** [comment]
my main complaint was that it looked too much like a _question_

**Comment by orangejenny** [comment]
@benrudolph Hrm, I think that looks weird, though it might be that I'm not used to it. Will think about it.
screen shot 2017-03-14 at 9 53 49 am

**Comment by benrudolph** [comment]
👍 trust your judgement. would recommend trying to do some real world app edits

**Comment by orangejenny** [comment]
It's growing on me...I do like that it does't line up quite so much with choice/questions, so it looks like something different, and there's more space on the left (think I tend to click on the left side of tree elements). Will merge.

**Comment by biyeun** [comment]
I definitely like @benrudolph's suggestion here more. Having it in line with the choice icon makes a lot more sense

**Pull request merged**
