### PR TITLE
upload xml file in standalone

### PR DESCRIPTION
**Pull request by emord**
image

cc: @biyeun

### CODE REVIEW

**Comment by millerdev** [comment]
Is that a button in a button?

What's the difference between this and pasting the file content into Tools > Edit Source XML?

**Comment by emord** [comment]
Removed btn class

image

There's not really a difference, but it's a lot faster to just upload a file than open it in a text editor and copy/paste it into there

**Comment by millerdev** [comment]
lol, what text editor do you use?

**Comment by emord** [comment]
vim, but until I can integrate vim into the web browser and use ggyG p to paste a file it's a lot easier to choose file -> select file than use mouse to copy xml -> click Edit source XML -> select all -> paste -> click update source

(can't always use reload last saved form because vellum can change ordering in setvalues, binds, etc. especially if you're changing thing in src and need to reload the page)

**Comment by millerdev** [comment]
>> lol, what text editor do you use?
>
> vim...

No worries, I was just kidding around. Good to merge when tests pass.

**Pull request merged**
