### PR TITLE
Warn before overwriting work

### PR DESCRIPTION
**Pull request by emord**
So I attempted to do this as a PID on a flight. @orangejenny brought this up in her field report. No HQ changes necessary.

I also attempted to do some work on automatically merging conflicts: https://github.com/dimagi/Vellum/compare/concurrent-editors

While that works suprisingly ok for non conflicting changes, I had to fix enough malformed XML to not recommend merging that, but it may give a starting point.

### CODE REVIEW

**Comment by amsagoff** [comment]
Can I be needy and ask you to attach a screenshot on the PR? Would be great to get user eyes on the wording/styling before deploy

**Comment by czue** [comment]
@amsagoff it's the same modal warning used elsewhere in vellum and the wording is right here: https://github.com/dimagi/Vellum/pull/289/files#diff-7eb52b366866677666470e019283c8eaR561

**Comment by amsagoff** [comment]
Like this one?

[image: Inline image 1]

Are the choices also "continue" or "abort"?

**Comment by millerdev** [comment]
screen shot 2015-01-06 at 8 10 52 am

**Comment by amsagoff** [comment]
whew, thanks daniel! Looks great :)

**Comment by millerdev** [comment]
I'm pushing this, along with #293, to prod today. @emord please submit a new PR to change the "Close" button to "Cancel" if that's not too hard.

**Pull request merged**
