### PR TITLE
Fix error on label itext with multiple refs

### PR DESCRIPTION
**Pull request by millerdev**
http://manage.dimagi.com/default.asp?236398

Review commits individually.

@emord cc @NoahCarnahan

### CODE REVIEW

**Comment by czue** [comment]
trouble sleeping?

**Comment by NoahCarnahan** [comment]
👍

**Comment by millerdev** [comment]
yep, couldn't sleep so I decided to finish the bug I had started earlier.

**Comment by czue** [comment]
> yep, couldn't sleep so I decided to finish the bug I had started earlier.

classic @millerdev

**Pull request merged**
