### PR TITLE
Move question ID into logic section

### PR DESCRIPTION
**Pull request by orangejenny**
@amsagoff green-lighted this

screen shot 2016-11-02 at 5 41 58 pm

### CODE REVIEW

**Comment by amsagoff** [comment]
Hold off on merge til we've figured out the docs - but I managed to get the
scope of the doc change down, so we can move forward on this in general!

**Comment by amsagoff** [comment]
Also checking - does ID get auto-filled?

**Comment by orangejenny** [comment]
It's initially set to `question1`, `question2`, etc. Nothing updates it after that.

**Comment by czue** [comment]
have we thought about, and decided that we don't care about the segment of people that might run into trouble analyzing their data if they don't realize that they should set proper question IDs ahead of time? just wondering if we should get more input on that question before releasing this.

**Comment by amsagoff** [comment]
I don't think we've properly thought through the implications of defaulting
question IDs to something non-meaningful. Jenny, let's regroup on this
offline?

**Comment by orangejenny** [comment]
Sure, sounds good.

**Comment by amsagoff** [comment]
(i think this is being addressed through form builder onboarding now)

**Comment by orangejenny** [comment]
yeah, closing this

**Pull request closed without merging**
