### PR TITLE
update icons from updated commcare hq font...

### PR DESCRIPTION
**Pull request by biyeun**
phase out old ones in prep for b3 upgrades...
also addresses http://manage.dimagi.com/default.asp?85272

### CODE REVIEW

**Comment by biyeun** [comment]
@millerdev updated and should be working now...

**Comment by millerdev** [comment]
Some of the buttons in the toolbar are now 1px too high (viewing in stand-alone again).

screen shot 2015-01-27 at 11 20 42 am

**Comment by biyeun** [comment]
@millerdev Please check your zoom. I can't reproduce that locally with a neutral zoom, but +1 I can.

**Comment by millerdev** [comment]
Thanks. Didn't even realize my page was zoomed.

**Pull request merged**
