### PR TITLE
Add advanced editor to fixture widget (flagged)

### PR DESCRIPTION
**Pull request by millerdev**
screenshot 2015-05-19 16 30 59

Spike on https://github.com/dimagi/Vellum/pull/417

@emord 
cc @kaapstorm

### CODE REVIEW

**Comment by emord** [comment]
Looks good to me. What do you think about disabling the filter widget whenever the lookup table isn't found? It seems really nasty that the last filter will be taken out of the query and inserted there, which is part of the reason I went for the stop gap first.

**Comment by millerdev** [comment]
Yeah, was kinda vacillating on that one. Not sure if it's worth the extra complexity only to accommodate advanced use cases. Were you thinking we'd make it tack that filter back on the query when you drop into advanced mode?

**Comment by emord** [comment]
@millerdev Updated to handle the filter nicely. Still doesn't support multiple filters

**Comment by emord** [comment]
g2m after tests

**Pull request merged**
