### PR TITLE
jQuery 3

### PR DESCRIPTION
**Pull request by orangejenny**
Somewhat surprisingly, tests passed without any code changes.

Hold off on merge until HQ is also ready to upgrade, which looks like it's going to be more of an undertaking.

@emord

### CODE REVIEW

**Comment by millerdev** [comment]
Test failed on both test runs: The rich text editor in vellum popovers should destroy popover after destroy. Kicked.

**Comment by orangejenny** [comment]
Hrm, I hope that test doesn't become a thorn in our side(s).

**Comment by millerdev** [comment]
failed again. it's timing out

**Comment by orangejenny** [comment]
Yeah, it's timing out rather consistently, will dig into it more.

Also realized that this breaks drag & drop, which our tests all fake at least a little bit.

**Comment by orangejenny** [comment]
Closing this for now, will re-visit after we get on jQuery 2.

**Pull request closed without merging**
