### PR TITLE
Grunt

### PR DESCRIPTION
**Pull request by emord**
Adding in a grunt file to watch changes and do automated testing and linting. would be nice to get builds in here instead of a make file as well, but that's a little larger

@millerdev 

cc: @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
niiice

**Comment by orangejenny** [comment]
the future is here.

**Comment by orangejenny** [comment]
would be nice to mention this in vellum's main README

**Comment by millerdev** [comment]
excellent! agree with @orangejenny on the README comment

**Pull request merged**
