### PR TITLE
Show date drag and drop on full screen

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?179699

code buddies: @proteusvacuum @esoergel

### CODE REVIEW

**Comment by orangejenny** [comment]
This looks like it's becoming a z-index arms race. Any idea why full screen has the high z-index in the first place?  @dannyroberts do you remember? I poked at it for a few minutes but didn't find the reason. Did notice that the saving modals also don't work in full screen mode.

**Comment by dannyroberts** [comment]
full screen has a high zindex because it is implemented by detaching the vellum main view (using css absolute/relative positioning) and it needs to appear above all other things on the page—except for dropdowns, modals etc that need to appear above the full screen view, which it sounds like I screwed that up.

**Comment by orangejenny** [comment]
@dannyroberts 

> it needs to appear above all other things on the page—except for dropdowns, modals etc that need to appear above the full screen view

Yeah, that exception is a killer, isn't it? For this case, the other styles (fixed position, full screen coordinates, opaque background) look like they're enough to cover up HQ. Was just wondering if you'd run into something specific that made the z-index also necessary, or if we could just drop it.

**Comment by dannyroberts** [comment]
Um, I do think there was something that at some point was awkwardly
floating on top of the full screen view, but I don't remember what that
was. Maybe you can git blame the zindex line to see if there's a commit
message explaining the reason. If it's just part of the original commit,
it's possible I'm wrong and that I just did that preemptively and forgot to
think harder about it.

**Comment by emord** [comment]
Did some more digging on this one.

Looks like `.modal-backdrop`'s `z-index: 1040`(that's the dark background that's used in saving that i think @orangejenny is talking about), and `.modal`'s `z-index: 1050`. 

Our different modals are children of `.modal`, but they are covered by the `.modal-backdrop` when < 1040. Not super obvious to me why that's happening right now.

**Comment by emord** [comment]
@orangejenny I think this accomplishes what we talked about earlier today

**Comment by orangejenny** [comment]
looks good. you tested this within HQ, right? (i'm surprised the fixed position isn't necessary)

**Comment by emord** [comment]
Well the fixed position is still there in `fd-ui-container`. The parent of that `#formdesigner` is what i removed the fixed from. So fixed is required, but it's now a sibling of the modals, so it doesn't screw with that

**Comment by orangejenny** [comment]
thanks for the explanation, i wasn't looking closely enough at the unchanged code

**Pull request merged**
