### PR TITLE
allow dash in case property

### PR DESCRIPTION
**Pull request by emord**
@esoergel http://manage.dimagi.com/default.asp?234164

### CODE REVIEW

**Comment by millerdev** [comment]
👍 on ✅

**Comment by millerdev** [comment]
Do you think it's worth adding a test for a case property with a dash to verify this actually works?

**Comment by esoergel** [comment]
woo!  Thanks J$, and thanks for the quick turnaround.

**Comment by emord** [comment]
Added/fixed some tests.

**Comment by millerdev** [comment]
👍 on ✅

**Comment by emord** [comment]
:white_check_mark:

**Pull request merged**
