### PR TITLE
Allow self reference in calculate

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?187877

code buddy: @TylerSheffels

### CODE REVIEW

**Comment by millerdev** [comment]
Would it be valid to have a calculate of `. + 1`? What would that mean? When does it get recalculated? My understanding is that bind calculates use some kind of continuous calculation mode. This either means that they are calculated when any of their dependencies change or that they are calculated just in time when they are needed (not sure which). If that is true, then it seems like the example above would either create an infinite calculation loop or erratically increment the calculated value each time it is referenced (undefined behavior?). If that is the case, then I imagine the warning was there to protect innocent users from dragging a question into its own calculate.

@ctsims may know the answer, or maybe he can correct my understanding of how calculates work.

It seems like we have had a few requests recently where it would be handy to show some warning message when a warning condition is created, but allow the user to dismiss it and not be bothered by it again. Not sure how hard this would be to implement (definitely harder than this PR), but this seems like a perfect place for it.

**Comment by TylerSheffels** [comment]
@emord I don't think I have appropriate context for this, so I will defer to @millerdev

**Comment by emord** [comment]
I think we're waiting on an answer from either @ctsims or @wpride to answer @millerdev question

**Comment by ctsims** [comment]
Calculates can't be self-referential. "X = X + 1" doesn't have a stable
value.

-Clayton

**Comment by wpride** [comment]
@ctsims @emord If the '.' is in the predicate (within '[' and ']') then it doesn't refer to current() and so is valid

**Comment by emord** [comment]
Closing this for now as it's a bit more work to only warn when not in filters.

**Pull request closed without merging**
