### PR TITLE
Add help placeholder

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?156218

selection_004

### CODE REVIEW

**Comment by emord** [comment]
There wasn't really another example of this type of help text in vellum. The other help texts were on the actual type of this question, where this was a help for one input in a question

**Comment by orangejenny** [comment]
This is kind of weird. Can we chat about it?

**Comment by orangejenny** [comment]
To be more articulate: I don't think that placeholders are a good place for information like this. Would much prefer we pick a standard for marking android-only functionality, which pops up all over HQ. Maybe the robot icon that we currently use for callout questions, with a hover that says "Android only"?

**Comment by amsagoff** [comment]
Agree with Jenny - though also this is under "advanced" so we really dont
have to put too much effort into the UX. Fine with removing any indication
it's android only if this is going to be an effort.

**Comment by emord** [comment]
I think this will be more effort to come up with a new standard way to do this than we would normally put in a qa bug ticket. I'll make a new ticket for coming up with something like this though.

**Pull request closed without merging**
