### PR TITLE
Help on focus

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?170957

Should wait on the [corresponding HQ PR](https://github.com/dimagi/commcare-hq/pull/7126).

@sravfeyn / @emord 

cc @amsagoff

### CODE REVIEW

**Comment by sravfeyn** [comment]
:+1:

**Comment by millerdev** [comment]
Is it possible to make the popup disappear when clicking on the question mark a second time? For example:

- Click question mark (do not move the mouse).
- Help popup is displayed.
- Click question mark (again).
- Help popup is hidden.

**Comment by orangejenny** [comment]
No. The options are
- hover
- click, where the popup is only closed if you click the icon again
- focus, where the popup is closed if you click anywhere other than the icon

I experimented with using both focus and click, hoping that would behave as you're describing, but it doesn't work.

**Comment by emord** [comment]
:+1: from me whenever hq gets merged

**Pull request merged**
