### PR TITLE
choice -> item as default

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?89892#1012375

Makes item1, item2, ... into choice1, choice2, .... by default

@amsagoff 

cc: @TylerSheffels

### CODE REVIEW

**Comment by amsagoff** [comment]
you mean the reverse :)

so satisfying to see this finally happen

**Comment by TylerSheffels** [comment]
Does this have any affect on existing forms?

**Comment by TylerSheffels** [comment]
If the answer to that question is no, which I assume it is, then G2M

**Comment by emord** [comment]
It shouldn't have any negative effect as these are just defaults. The only change would be if someone had a choices that were item1 item2 then a new choice would be choice1, choice2, but people usually change those anyways

There's actually still references to item1, item2 in tests that I didn't change, so having non-choice1 names should still be tested.

**Pull request merged**
