### PR TITLE
Form comments hacked together

### PR DESCRIPTION
**Pull request by emord**
@czue threw this together in a couple minutes. Is this something like you were talking about?

image

Would need some cleanup/tests. Could also probably throw it in itext just as easily if we wanted it to be able to have different languages (assuming somethign like `value=comment` doesn't mean anything to mobile)

### CODE REVIEW

**Comment by czue** [comment]
it's close to what I was thinking. how are you thinking people edit them?

**Comment by czue** [comment]
re: itext, one other downside of using something real that goes to phone is performance (size of forms, possible runtime of forms). not sure if that's a real concern or not.

**Comment by czue** [comment]
(awesome how quick this was though!)

**Comment by emord** [comment]
> it's close to what I was thinking. how are you thinking people edit them?

It's just another text box. (stuck it in advanced right now)

**Comment by czue** [comment]
ah nice. yeah then this is exactly what i was thinking

**Comment by emord** [comment]
Verified that HQ will strip out the comment and tests are passing

@dimagi/product any feedback on this feature?

**Comment by sheelio** [comment]
Is this to allow users to add comments to questions?  Does that comment display support markdown?

**Comment by emord** [comment]
Yes it's to add comments to questions. @czue was saying it would be a super useful feature. It doesn't support markdown, but it could (would be a bit more work to get a preview window though)

**Comment by amsagoff** [comment]
Awesome! Pro releasing this as is (a textbox in advanced) and iterating
based on feedback from FMs, who are pretty much the target users.

**Comment by czue** [comment]
:tada: :balloon: :confetti_ball:

**Comment by czue** [comment]
@kaapstorm @snopoke fyi from summit talks

**Comment by kaapstorm** [comment]
This is great!

**Comment by snopoke** [comment]
suite!

**Pull request merged**
