### PR TITLE
Make collapsing decisions sticky

### PR DESCRIPTION
**Pull request by orangejenny**
In question properties, collapse all sections by default except for Basic. Then, whenever someone collapses or expands a section, remember that decision and respect it in the future.

Quick and dirty and testless, since the failure mode of this is not a big deal.

cc @calellowitz

### CODE REVIEW

**Comment by orangejenny** [comment]
@emord

**Comment by orangejenny** [comment]
fyi @dimagi/product

**Comment by orangejenny** [comment]
> Does this need sign off from @dimagi/product ?

Wouldn't hurt. I don't think Amelia ever weighed in on the slack conversation.

**Comment by amsagoff** [comment]
how does "remembering the decision" work? Is it per-session?

**Comment by orangejenny** [comment]
It's remembered forever, but is specific to the user's browser.

**Comment by amsagoff** [comment]
Nice!

**Pull request merged**
