### PR TITLE
hide spinner on save

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?176493

### CODE REVIEW

**Comment by orangejenny** [comment]
tests pass locally...

**Comment by millerdev** [comment]
Rebased on latest master, hoping that makes travis happy.

**Comment by millerdev** [comment]
Had to pin mocha-phantomjs at 3.5.3 because 3.5.4 appears to need a version of phantomjs that was not available.

**Comment by orangejenny** [comment]
thanks, @millerdev

**Pull request merged**
