### PR TITLE
Escape mug display name

### PR DESCRIPTION
**Pull request by emord**
Escaping the mugs display name 

The fun things you can do without this:

out

out-1

### CODE REVIEW

**Comment by millerdev** [comment]
How did you stumble upon this?

**Comment by emord** [comment]
There was a bug for for <output value> in labels. I noticed it was blank in the tree. Inspected the element and saw that they were just being inserted as html.

So naturally I defaced HQ with marquee rainbows. Also I found out that Chrome disabled blink tags.

Also inserting javascript does nothing.

**Comment by emord** [comment]
Actually I take that back. Arbitrary javascript can be run on form load

**Comment by millerdev** [comment]
> So naturally I defaced HQ with marquee rainbows.

quote of the week!

**Pull request merged**
