### PR TITLE
Expand parent groups when showing in tree

### PR DESCRIPTION
**Pull request by millerdev**
@emord @orangejenny cc @benrudolph

### CODE REVIEW

**Comment by orangejenny** [comment]
Thank you for fixing! I had mentally added this to my backlog but hadn't actually grabbed the ticket.

Test would be nice if it's feasible; there's a test for the basic behavior at https://github.com/dimagi/Vellum/blob/master/tests/richText.js#L621

**Comment by millerdev** [comment]
heh, I thought about adding a test and then decided it wasn't worth it because I'm not sure we have a good way to detect if branches of the tree are collapsed or expanded... but I'll take a stab at it since you asked

**Comment by millerdev** [comment]
@orangejenny added test: 60dcd80

**Comment by orangejenny** [comment]
lovely, looks good to me

**Pull request merged**
