### PR TITLE
upgrade underscore

### PR DESCRIPTION
**Pull request by orangejenny**
Created this a while back, thought tests were failing, but they seem to pass (locally, at least) now.

@emord

### CODE REVIEW

**Comment by emord** [comment]
how comfortable are you upgrading the entire app manager? https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/templates/app_manager/form_designer.html#L123

**Comment by millerdev** [comment]
new PR: https://github.com/dimagi/commcare-hq/pull/12899

looking forward to this!

**Comment by orangejenny** [comment]
Good to merge.

**Comment by millerdev** [comment]
woohoo!

**Pull request merged**
