### PR TITLE
Bump markdown-it version

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Summary

Upgrade Mardown-it on Vellum as we are upgrading the version on HQ also https://github.com/dimagi/commcare-hq/pull/28922
## Product Description

This won't change anything for user.
## Safety Assurance

- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [X] If QA is part of the safety story, the "Awaiting QA" label is used
- [X] I am certain that this PR will not introduce a regression for the reasons below

### QA Plan

QA Plan would be same as we are doing in HQ https://github.com/dimagi/commcare-hq/pull/28922
### Safety story

The changes are pretty safe and have been tested on local and staging.
### Rollback instructions
Rolling back the version would do the trick.

- [X] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
Can you add notes on what you checked to verify that this is a safe upgrade? Also, is there a reason why you didn't fill the risk factor checklist? Is QA planned?

**Comment by AmitPhulera** [comment]
Oh! I just wanted to get it out on staging and test it there, I created a PR from Github in my browser and then later forgot to update the description.

I have updated the description and QA for the change is already undergoing and QA team is working on it.

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
Thanks. Good to merge after QA pass.

**Comment by AmitPhulera** [comment]
QA passed successfully. Merging it to master.

**Pull request merged**
