### PR TITLE
Fix lost changes

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?217896#1093575
https://github.com/dimagi/Vellum/pull/617#issuecomment-186309022

this bug only shows up in the new editor. I've been sitting on this fix for a few days, because I haven't had a chance to bootstrap the expression editor tests that support rich text yet

@millerdev @gcapalbo

### CODE REVIEW

**Comment by orangejenny** [comment]
Curious what the bug was: the rich text editor was validating too frequently and this caused problems?

**Comment by millerdev** [comment]
heh, I agree a test for this would be nice, but those tests are a mess.

**Comment by emord** [comment]
> Curious what the bug was: the rich text editor was validating too frequently and this caused problems?

@orangejenny the bug isn't actually about validating the expresion, but `validateExpression` also sets a flag to warn the user when they have made changes to the expression in the expression editor, and that wasn't being set

**Comment by orangejenny** [comment]
ah, makes sense, thanks

**Pull request merged**
