### PR TITLE
Add option to display question tree as IDs

### PR DESCRIPTION
**Pull request by orangejenny**

### CODE REVIEW

**Comment by orangejenny** [comment]
@millerdev Oof, I didn't even notice that "(_ids)" was displaying. Fixed that, and addressed other comments.

**Comment by amsagoff** [comment]
[?]

**Comment by orangejenny** [comment]
@amsagoff Objections? Concerns?

**Comment by amsagoff** [comment]
nope - looks great with daniel's suggestions! Excited to see your idea
become reality

**Comment by millerdev** [comment]
One more thing. The Display chooser is not visible if there is only one language on the form. You can test this in the stand-alone version by temporarily changing [tests/options.js](https://github.com/dimagi/Vellum/blob/master/tests/options.js#L88)

```js
        javaRosa: {
            langs: ['en'], //'hin'],
            displayLanguage: 'en'
        },
```

**Comment by orangejenny** [comment]
@millerdev Good catch, thank you. Fixed now.

The return statement should now never execute, so I could have just deleted it, but figured maybe someone will remove or change the _ids logic at some point.

**Pull request merged**
