### PR TITLE
New style incorporating data browser

### PR DESCRIPTION
**Pull request by millerdev**
This builds on #474. Wait to merge until questions on that PR are answered.

Possibly easier to review my additions commit-by-commit.

@biyeun 
cc @kaapstorm

### CODE REVIEW

**Comment by millerdev** [comment]
QA ticket http://manage.dimagi.com/default.asp?175812

**Comment by emord** [comment]
https://github.com/dimagi/Vellum/pull/474#discussion_r33789541

@biyeun @millerdev I assume if it passed QA those are in HQ? (I think that's the only open question)

**Comment by biyeun** [comment]
@amsagoff 
There was a question about docs in the ticket, is this still good to merge regardless?

**Comment by biyeun** [comment]
also :+1: saw it on staging and looks amazeballs

**Comment by amsagoff** [comment]
good to merge, jeremy is working on docs but they shouldnt be a blocker

**Comment by emord** [comment]
good to merge from me. Will wait until the don't merge ticket is removed though.

@millerdev did you want to make the changes we talked about to app resources in this PR or a new one?

**Comment by millerdev** [comment]
> did you want to make the changes we talked about to app resources in this PR or a new one?

Earlier Skype message from Emord
>> Should the app resources panel be hidden if there is no information returned? Currently it still shows up

This is a little tricky. The app resources tree displays a loading indicator while data sources are loading. It feels a little awkward to hide the tree once the sources are loaded and the data browser discovers that there is nothing to display. I suppose it could display a placeholder indicating that there are no app resources? Seems like an empty pane already communicates that, and with less visual noise. Thoughts?

**Comment by amsagoff** [comment]
seems like something we can resolve in a different PR, since that's
currently behind a flag anyway? Don't want to block the sweet new UI from
going out!

**Comment by emord** [comment]
@millerdev I actually meant the things like the minimize button and changing scroll bar we talked about in the meeting on Tuesday. Still easily done in another pr though

**Pull request merged**
